apiVersion: v1
kind: Namespace
metadata:
  name: mailpit
---
apiVersion: v1
kind: Pod
metadata:
  name: mailpit
  namespace: mailpit
  labels:
    app: mailpit
spec:
  containers:
    - name: mailpit
      ## image: ghcr.io/axllent/mailpit:v1.27.6@sha256:7496188a4de82d780b3cb4693367bb9791d9358660590dd746f6354d450107b0  ## ARM64
      image: ghcr.io/axllent/mailpit:v1.27.6
      ports:
        - containerPort: 8025
        - containerPort: 1025
      env:
        - name: MP_MAX_MESSAGES
          value: "5000"
        - name: MP_SMTP_AUTH_ACCEPT_ANY
          value: "1"
        - name: MP_SMTP_AUTH_ALLOW_INSECURE
          value: "1"
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
          ephemeral-storage: 1Gi
        limits:
          cpu: 200m
          memory: 128Mi
          ephemeral-storage: 2Gi
      volumeMounts:
        - name: work
          mountPath: /work
  volumes:
    - name: work
      emptyDir:
        sizeLimit: 2Gi
