apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
  name: efs.csi.aws.com
spec:
  attachRequired: false
  fsGroupPolicy: File
  podInfoOnMount: false
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
