apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: aelwdhhuo2pz4f
        access: proxy
        url: http://prometheus-server:9090
        isDefault: true
---
apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: grafana-dashboards-provider  
data:  
  dashboards.yml: |  
    apiVersion: 1

    providers:  
      - name: 'MongoDB Dashboards'  
        orgId: 1  
        folder: ''  
        type: file  
        disableDeletion: false  
        updateIntervalSeconds: 10  
        allowUiUpdates: true  
        options:  
          path: /var/lib/grafana/dashboards  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards-json
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-data
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards-provider
          configMap:
            name: grafana-dashboards-provider
        - name: grafana-dashboards-json
          configMap:
            name: grafana-dashboards-json
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: mongodb
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
  allocateLoadBalancerNodePorts: true
  sessionAffinity: None
  publishNotReadyAddresses: true
  type: LoadBalancer
---
