apiVersion: v1
kind: ConfigMap
metadata:
  name: rsbackup
  namespace: mongodb
data:
  baseUrl: https://ops-manager-svc.mongodb.svc.cluster.local:8443
  projectName: rsbackup
  orgId: 111111111111111111111111
  sslMMSCAConfigMap: ca-issuer
  tlsRequireValidMMSServerCertificates: 'false'
  sslRequireValidMMSServerCertificates: 'false'
---
apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
  namespace: mongodb
stringData:
  publicKey: abcdefghi
  privateKey: 11111111-2222-3333-4444-555555555555
---
