apiVersion: v1
kind: Service
metadata:
  name: ops-manager-svc-ext
  namespace: mongodb
  labels:
    app: ops-manager-svc
    controller: mongodb-enterprise-operator
    mongodb.com/v1.mongodbOpsManagerResourceOwner: ops-manager
spec:
  allocateLoadBalancerNodePorts: true
  sessionAffinity: None
  publishNotReadyAddresses: true
  type: LoadBalancer
  ports:
    - name: mongodb
      nodePort: 32190
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: ops-manager-svc
    controller: mongodb-enterprise-operator
