apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  topology: SingleCluster
  replicas: 1
  version: 8.0.14
  adminCredentials: adminusercredentials

  externalConnectivity:
    type: LoadBalancer

  security:
    certsSecretPrefix: "om"
    tls:
      ca: "ca-issuer"

  applicationDatabase:
    featureCompatibilityVersion: "8.2"
    members: 3
    passwordSecretKeyRef:
      key: password
      name: opsmanagereks-db-om-password
    topology: SingleCluster
    version: 8.2.0-ent
    security:
      certsSecretPrefix: "appdb"
      tls:
        ca: "ca-issuer"

  backup :
    enabled: true
    externalServiceEnabled: false
    members: 1

    headDB:
      storage: "5Gi"

    s3OpLogStores:
    - name: s3oplog
      irsaEnabled: true
      pathStyleAccessEnabled: true
      s3BucketEndpoint: ${s3BucketEndpoint}
      s3BucketName: ${s3BucketName}
      mongodbResourceRef:
        name: rsbackup
      mongodbUserRef:
        name: backupuser

    s3Stores:
    - name: s3blockStore
      irsaEnabled: true
      pathStyleAccessEnabled: true
      s3BucketEndpoint: ${s3BucketEndpoint}
      s3BucketName: ${s3BucketName}
      mongodbResourceRef:
        name: rsbackup
      mongodbUserRef:
        name: backupuser

  configuration:
    mms.ignoreInitialUiSetup: "true"
    mms.centralUrl: https://ops-manager-svc.mongodb.svc.cluster.local:8443
    mms.adminEmailAddr: a@b.com
    mms.fromEmailAddr: a@b.com
    mms.mail.hostname: mailpit-svc-ext.mailpit.svc.cluster.local
    #mms.mail.user: apikey
    #mms.mail.password: randomcharstring
    mms.mail.port: "1025"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
    mms.minimumTLSVersion: TLSv1.2
    mms.replyToEmailAddr: a@b.com
    mms.security.allowCORS: "false"
    mms.mongoDbUsage.defaultUsageType: DEV_SERVER
    mms.featureFlag.disableDiscoveryIpAddressAliases: "enabled"
    mongodb.release.autoDownload.enterprise: "true"
    #automation.versions.source: mongodb

  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-ops-manager
              resources:
                requests:
                  cpu: "0.5"
                  memory: "2Gi"
                limits:
                  cpu: "1"
                  memory: "4Gi"
