kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  provisioningMode: efs-ap
  fileSystemId: ${fileSystemId}
  directoryPerms: "777"
  uid: "2000"
  gid: "2000"
