apiVersion: v1
kind: ConfigMap
metadata:
  name: rsbackup
  namespace: mongodb
data:
  baseUrl: https://ops-manager-svc.mongodb.svc.cluster.local:8443
  projectName: rsbackup
  orgId: 6a57bc3feb738c447f2e3d61
  sslMMSCAConfigMap: ca-issuer
  tlsRequireValidMMSServerCertificates: 'false'
  sslRequireValidMMSServerCertificates: 'false'
---
apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
  namespace: mongodb
stringData:
  publicKey: sigxrnyh
  privateKey: 09576fa5-ce59-46ce-9f9c-3ad1faf2721b
---
