apiVersion: v1
kind: ConfigMap
metadata:
  name: rsbackup
  namespace: mongodb
data:
  baseUrl: https://ops-manager-svc.mongodb.svc.cluster.local:8443
  projectName: rsbackup
  orgId: 68adb3c69ce2de55addd57df
  sslMMSCAConfigMap: ca-issuer
  tlsRequireValidMMSServerCertificates: 'false'
  sslRequireValidMMSServerCertificates: 'false'
---
apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
  namespace: mongodb
stringData:
  publicKey: xrmdhegh
  privateKey: d9450e20-11ca-49f7-b41f-90b2ec571b38
---
