apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  topology: SingleCluster
  replicas: 1
  version: 8.0.6
  adminCredentials: adminusercredentials

  externalConnectivity:
    type: LoadBalancer

  #security:
  #  certsSecretPrefix: "om"
  #  tls:
  #    ca: "ca-issuer"

  applicationDatabase:
    featureCompatibilityVersion: "8.0"
    members: 3
    passwordSecretKeyRef:
      key: password
      name: opsmanagereks-db-om-password
    topology: SingleCluster
    version: 8.0.6-ent
    #security:
    #  certsSecretPrefix: "appdb"
    #  tls:
    #    ca: "ca-issuer"

  backup:
    enabled: false

  configuration:
    mms.ignoreInitialUiSetup: "true"
    mms.centralUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080
    mms.adminEmailAddr: a@b.com
    mms.fromEmailAddr: a@b.com
    mms.mail.hostname: mailpit-svc-ext.mailpit.svc.cluster.local
    #mms.mail.user: apikey
    #mms.mail.password: randomcharstring
    mms.mail.port: "1025"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
    mms.minimumTLSVersion: TLSv1.2
    mms.replyToEmailAddr: a@b.com
    mms.security.allowCORS: "false"
    mms.mongoDbUsage.defaultUsageType: DEV_SERVER
    mms.featureFlag.disableDiscoveryIpAddressAliases: "enabled"
    mongodb.release.autoDownload.enterprise: "true"
    #automation.versions.source: mongodb

  statefulSet:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: disktype
                      operator: In
                      values:
                        - ssd
          containers:
          - name: mongodb-ops-manager
            resources:
              limits:
                cpu: "1"
                memory: 4Gi
              requests:
                cpu: "0.5"
                memory: 1Gi
          metadata:
            annotations:
              key1: value1